CREATE TABLE IF NOT EXISTS jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source TEXT NOT NULL,
    external_id TEXT NOT NULL,
    url TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    company_url TEXT,
    company_logo TEXT,
    description TEXT NOT NULL DEFAULT '',
    salary TEXT,
    experience TEXT,
    vacancies TEXT,
    category TEXT,
    career_level TEXT,
    job_requirements TEXT,
    job_type TEXT,
    area TEXT,
    posted_at TEXT,
    collected_at TEXT NOT NULL,
    fit_score REAL NOT NULL DEFAULT 0,
    fit_reasons TEXT NOT NULL DEFAULT '[]',
    extra_json TEXT NOT NULL DEFAULT '{}'
);
